### PR TITLE
Inline process changes.

### PR DESCRIPTION
**Pull request by Mistuke**
Inline the fix process waiting code such that when older process libraries are used hsc2hs still behaves properly.

The problem is that during a GHC bootstrap the bootstrapping compiler will use a broken process and so hsc2hs won't be working correctly.

/CC @bgamari

### CODE REVIEW

File: Compat/Process.hs [hunk 1]
```diff
@@ -0,0 +1,120 @@
+{-# LANGUAGE CPP #-}
+#if __GLASGOW_HASKELL__ >= 704
+{-# LANGUAGE Safe #-}
+#endif
+{-# LANGUAGE InterruptibleFFI #-}
```
Comment (RyanGlScott) [inline Compat/Process.hs]: Alas, `InterruptibleFFI` wasn't introduced until GHC 7.2, so this line currently breaks the Linux CI build on 7.0.

Perhaps we can work around this easily enough, however. This code should only be necessary on Windows, and because we require `process-1.5` as the minimum (which needs 7.2 or later to be compiled) on Windows, perhaps it would suffice to guard this line with `#if NEEDS_PROCESS_WORKAROUND`.

**Comment by Mistuke** [comment]
That should do it, I'm off to work so won't be able to reply again until tonight :)

**Comment by RyanGlScott** [comment]
Thanks, @Mistuke!

@bgamari, can you confirm that this is sufficient to fix https://gitlab.haskell.org/ghc/ghc/issues/17480?

**Comment by bgamari** [comment]
For the record, this is being tested here: https://gitlab.haskell.org/ghc/ghc/merge_requests/2199.

**Comment by bgamari** [comment]
Unfortunately this makes Darwin unhappy:
```

utils/hsc2hs/Compat/Process.hs:9:5: error:
     error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
  |
9 | #if NEEDS_PROCESS_WORKAROUND
  |     ^
#if NEEDS_PROCESS_WORKAROUND
mv libffi/libffi-* libffi/build
    ^
```
I'll push a fix.

**Comment by bgamari** [comment]
Closing in favor of #40.
