### ISSUE TITLE
hsc2hs does not compile from git tree: Data constructor not in scope: CURRENT_PACKAGE_VERSION :: [Char]

### ISSUE THREAD

**Issue by trofi** [haskell/hsc2hs#6]
Tried to build standalone hsc2hs to debug https://ghc.haskell.org/trac/ghc/ticket/14889

```
[sf] ~/dev/git/hsc2hs:cabal configure
Resolving dependencies...
Configuring hsc2hs-0.68.3...
[sf] ~/dev/git/hsc2hs:cabal build
Building hsc2hs-0.68.3...
Preprocessing executable 'hsc2hs' for hsc2hs-0.68.3...
[ 1 of 10] Compiling Paths_hsc2hs     ( dist/build/autogen/Paths_hsc2hs.hs, dist/build/hsc2hs/hsc2hs-tmp/Paths_hsc2hs.o )
[ 2 of 10] Compiling HSCParser        ( HSCParser.hs, dist/build/hsc2hs/hsc2hs-tmp/HSCParser.o )
[ 3 of 10] Compiling Flags            ( Flags.hs, dist/build/hsc2hs/hsc2hs-tmp/Flags.o )
[ 4 of 10] Compiling Common           ( Common.hs, dist/build/hsc2hs/hsc2hs-tmp/Common.o )
[ 5 of 10] Compiling C                ( C.hs, dist/build/hsc2hs/hsc2hs-tmp/C.o )
[ 6 of 10] Compiling UtilsCodegen     ( UtilsCodegen.hs, dist/build/hsc2hs/hsc2hs-tmp/UtilsCodegen.o )
[ 7 of 10] Compiling DirectCodegen    ( DirectCodegen.hs, dist/build/hsc2hs/hsc2hs-tmp/DirectCodegen.o )
[ 8 of 10] Compiling ATTParser        ( ATTParser.hs, dist/build/hsc2hs/hsc2hs-tmp/ATTParser.o )
[ 9 of 10] Compiling CrossCodegen     ( CrossCodegen.hs, dist/build/hsc2hs/hsc2hs-tmp/CrossCodegen.o )
[10 of 10] Compiling Main             ( Main.hs, dist/build/hsc2hs/hsc2hs-tmp/Main.o )

Main.hs:69:38: error:
    Data constructor not in scope: CURRENT_PACKAGE_VERSION :: [Char]
```

**Comment by trofi** [comment]
Looks like breakage was introduced by 9c13b192ae9f0eb3b445fa9d310b2b9f4197b735

```
-versionString = "hsc2hs version " ++ showVersion version ++ "\n"
+versionString = "hsc2hs version " ++ CURRENT_PACKAGE_VERSION ++ "\n"
```

**Comment by hvr** [comment]
which version of `cabal` did you use?

**Comment by hvr** [comment]
@trofi thanks for spotting this; should be fixed now, please reopen if it isn't.

**Comment by trofi** [comment]
Works now. Thank you! (using `cabal-1.24` locally)
